In [1]:
import cv2
import numpy as np

In [10]:
path = r"C:\Users\amitk\Downloads\images_ml\c.webp"
img = cv2.imread(path)
print(img)
# print(img.shape)
cv2.imshow("image",img)
cv2.waitKey(0)

cv2.destroyAllWindows()

# 0 (black) to 255 (white). pixelcolor range

[[[60 68 78]
  [60 68 78]
  [59 68 81]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 5  5  3]]

 [[51 58 66]
  [64 72 83]
  [66 74 84]
  ...
  [ 5  5  3]
  [ 5  5  3]
  [ 0  1  0]]

 [[21 26 32]
  [31 36 42]
  [49 55 63]
  ...
  [ 6  7  4]
  [ 6  7  4]
  [ 0  1  0]]

 ...

 [[10 14 16]
  [12 16 18]
  [13 17 19]
  ...
  [55 69 89]
  [55 69 89]
  [55 69 89]]

 [[10 14 16]
  [12 16 18]
  [13 17 19]
  ...
  [58 70 90]
  [58 70 90]
  [58 70 90]]

 [[10 14 16]
  [12 16 18]
  [13 17 19]
  ...
  [58 70 90]
  [58 70 90]
  [58 70 90]]]


In [57]:
path = r"C:\Users\amitk\Downloads\images_ml\c.webp"
img = cv2.imread(path,0)
print(img)

cv2.imshow("image",img)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[70 70 71 ...  0  0  4]
 [60 74 76 ...  4  4  1]
 [27 37 57 ...  6  6  1]
 ...
 [14 16 17 ... 73 73 73]
 [14 16 17 ... 75 75 75]
 [14 16 17 ... 75 75 75]]


In [9]:
matx = np.zeros((400,200))
print(matx)
cv2.imshow('Image',matx)
cv2.waitKey(0)

cv2.destroyAllWindows()


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
path = r"C:\Users\amitk\Downloads"
img_name = "c.webp"

img = cv2.imread(path+'\\'+img_name)

cv2.imshow('Image',img)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [19]:
img = cv2.imread(path+'\\'+img_name)

img = cv2.resize(img,(500,400))

cv2.imshow('Image',img)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [45]:
import os


In [41]:
img_names = os.listdir(r'C:\Users\amitk\Downloads\images_ml')

for img_name in img_names:
  img = cv2.imread(path+'\\'+img_name)
  img = cv2.resize(img,(500,400))
  cv2.imshow('Image',img)
  cv2.waitKey(0)

cv2.destroyAllWindows()

In [52]:
img_names = os.listdir(r'C:\Users\amitk\Downloads\images_ml')

for img_name in img_names:
  img = cv2.imread(path+'\\'+img_name)
  img = cv2.resize(img,(300,200))
  img_2 = np.hstack((img,img))
  img_3 = np.vstack((img_2,img_2))
  cv2.imshow('Image',img_3)
  cv2.waitKey(0)

cv2.destroyAllWindows()